import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AdminNav from '@/features/common/AdminNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="flex-shrink-0 w-64">
            <AdminNav />
          </div>

          <div className="mx-16 my-12">{children}</div>
        </div>
      </body>
    </html>
  );
}
